### ISSUE TITLE
bsc fork ganache 7.0.0 alpha 2 on m1 very slow

### ISSUE THREAD

**Issue by NikZak** [ConsenSys-archive/ganache#1609]
Sorry, for a poorly formulated issue. I need to install the alpha version as apparently it has the 'Number can only safely store up to 53 bits' issue solved. So I tried to install in a docker and I get two issues on my Apple M1:

First this:
```
ganache_1    | This version of µWS is not compatible with your Node.js build:
ganache_1    | 
ganache_1    | Error: Cannot find module './uws_linux_arm64_102.node'
ganache_1    | Falling back to a NodeJS implementation; performance may be degraded.
```
Not critical, but maybe related to the second issue: All the eth_calls to a bsc fork that I make become extremely slow. I can bearly make one and always get a time out on the second call (which was working fine in the ganache docker v6.12.2). In v6.12.2 I could do a hundred calls with no problem.

**Comment by davidmurdoch** [comment]
Are you able to provide a reproduction?
